config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :homes
  # root 'projects#index'
  devise_for :users
  resources :users
  resources :tasks

  resources :projects do
    resources :tasks
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
  attribute :status, :string, default: "Proposed"

  # Validation
  validates :status, :name, :description, presence: true
  validates :status, :name, :description, numericality: false

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user

  # Validation
  validates :status, :name, :task, presence: true
  validates :status, :name, :task, numericality: false
end

app/models/user.rb
class User < ApplicationRecord
  attribute :admin, :boolean, default: false
  has_many :projects
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validation
  validates :username, uniqueness: true
  validates :admin, absence: true
  validates :email, :name, :username, :years_exp, :prog_lang, :country, presence: true
  # validates :email, :name, :username, :prog_lang, :country, numericality: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :email, :admin, :prog_lang, :country])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :email, :admin, :prog_lang, :country])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    
    def index
        @projects = Project.all.order(:id)
    end

    def edit
        set_project
    end

    def show
        set_project
    end

    def new
        @project = Project.new
    end
  
    def create
        project = current_user.projects.create(project_params)
        redirect_to projects_path
    end

    def update
        puts params
        project = Project.find(params[:id])
        project.update(project_params)
        redirect_to project_path
    end

    def destroy
        Project.find(params[:id]).destroy
        redirect_to projects_path
    end

    private

    def set_project
        @project = Project.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:name, :status, :description)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all.order(:id)
    end

    def edit
        @task = Task.find(params[:id])
        @project_id = params[:project_id]
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = Task.new
    end
  
    def create
        @project = Project.find(params[:project_id])
        @task = @project.tasks.new(params.require(:task).permit(:name, :status, :task, :username, :created_at))
        @task.user_id = current_user.id
        @task.save
        redirect_to request.referrer
    end

    def update
        task = Task.find(params[:id])
        task.update(task_params)
        redirect_to project_path(params[:project_id])
    end

    def destroy
        Task.find(params[:id]).destroy
        redirect_to request.referrer
    end

    private
    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:name, :status, :task)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # has to be shown only for admin
    def index
        @users = User.all.order(:id)
    end
    def edit
        @user = User.find(params[:id])
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        User.find(params[:id]).destroy
        redirect_to user_path
    end

    private
    def user_params
        params.require(:user).permit(:email, :username, :name, :prog_lang, :country)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag("3.jpg", class:"d-block w-100" ) %>
    <div class="carousel-caption d-none d-md-block">
      <h1>We try to provide best services to manage your projects</h1>
    </div>
    </div>
      <div class="carousel-item">
      <%= image_tag("2.jpg", class:"d-block w-100" ) %>
      <div class="carousel-caption d-none d-md-block">
        <h1>Acheivements comes with cooperation</h1>
      </div>
    </div>
    <div class="carousel-item">
    <%= image_tag("1.jpg", class:"d-block w-100" ) %>
    <div class="carousel-caption d-none d-md-block">
      <h1>Start your business using our site</h1>
    </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<%# <h1>All rights are reserves </h1> %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <%= link_to('Project Management', root_path, class: 'nav-item nav-link active navbar-brand') %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to('Projects', projects_path, class: 'nav-item nav-link active') %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to('New Project', new_project_path, class: 'nav-item nav-link active') %>
      </li>
      <li class="nav-item">
        <%= link_to("Log out", destroy_user_session_path, method: :delete, class: 'nav-item nav-link active') %>
      </li>
      <li class="nav-item">
        <%= link_to("Profile", user_path(current_user), class: 'nav-item nav-link active') %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to("Login", new_user_session_path, class: 'nav-item nav-link active') %>
      </li>
      <li class="nav-item">
        <%= link_to("SignUp", new_user_registration_path, class: 'nav-item nav-link active') %>
      <li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <div class="form-group">
      <%= f.label :name, 'Name'%>
      <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :description, 'Description' %>
      <%= f.text_area :description, :class => "form-control",:rows => 5 %>
  </div>

  <%= f.button :submit, :class => "btn btn-success" %>
  <%= link_to 'Back', projects_path, class: "btn btn-primary"%>

<% end %>

app/views/projects/edit.html.erb
<h1 class="h1">Edit <%= @project.name %> Project</h1>

<%= render 'projects/form' %>

app/views/projects/index.html.erb
<p class="notice "><%= notice %></p>
<h1 class="h1">All Projects</h1>
<% if user_signed_in? %>
  <%= link_to "Add New Project", new_project_path, { :class => "btn btn-light" } %>
<% end %>
<br><br>
<table class="table table-striped">
  <thead class="thead-dark">
    <th scope="col">Project name</th>
    <th scope="col">By</th>
    <th scope="col">Status</th>
    <th scope="col">Posted at</th>
    <th scope="col">Edit</th>
    <th scope="col">Destroy</th>
  </thead>
  <% @projects.each do |project| %>
      <tr scope="row">
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= link_to project.user.name, user_path(project.user) %></td>
        <td><%= project.status %></td>
        <td><%= project.created_at.strftime("%d/%m/%Y") %></td>
        <% if user_signed_in? %>
          <% if current_user == project.user || current_user.admin %>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'You sure??' } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1 class="h1">New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    

<h1><%= @project.name %> Project</h1>
<h4>Owner: <%= link_to @project.user.name, user_path(@project.user) %></h4>
<h4>Project status: <%= @project.status %></h4>
<% if current_user == @project.user %>
    <%= form_for @project do |f| %>
    <div class="">
      <%= f.label :status, 'Change status:'%>
      <%= f.select :status, ['Proposed', 'Active', 'Done'], selected: 'Proposed' %>
    </div>
    <%= f.submit "Submit New Status", :class => "btn btn-light" %>
    <% end %>
      <%= link_to 'Edit Project', edit_project_path, class: "btn btn-light" %>
<% end %>
<p><%= @project.description %></p>
    </div>

    <div class="col">
    <table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <%# <th>Nom</th> %>
      <th>Task name</th>
      <th>Task</th>
      <th>By</th>
      <th>Status</th>
      <th>Posted at</th>
      <th>Edit</th>
      <th>Destroy</th>
      <th>Create</th>
    </tr>
  </thead>
  <tbody>
  <% @project.tasks.each do |task| %>
      <tr>
        <td scope="row"><%= task.name %></td>
        <td><%= task.task %></td>
        <td><%= task.user.name %></td>
        <td><%= task.status %></td>
        <td><%= task.created_at.strftime("%d/%m/%Y") %></td>
        <% if user_signed_in? %>
          <% if current_user == @project.user %>
              <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
              <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'You sure??' } %></td>
          <% else %>
              <td></td>
              <td></td>
          <% end %>
          <td></td>
        <% end %>
      </tr>
  <% end %>
  <% if user_signed_in? %>
    <tr>
    <%= render partial: 'tasks/form' %>
    </tr>
  </tbody>
  <% end %>
</table>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @project, @project.tasks.build ], local: true) do |f| %>
    <td><%= f.select :name, ['Analyse', 'Design DB', 'Design Front-End', 'Coding Back-End'] %></td>
    <td><%= f.text_field :task %></td>
    <td><%= f.label current_user.username %></td>
    <td><%= f.select :status, ['Pending', 'In Progress', 'Done'], selected:'In Progress' %></td>
    <td><%= f.label Time.now.strftime("%d/%m/%Y") %></td>
    <td></td>
    <td></td>
    <td><%= f.submit "Submit" %></td>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>

  <div class="form-group">
      <%= f.label :name, 'Name'%>
      <%= f.select :name, ['Analyse', 'Design DB', 'Design Front-End', 'Coding Back-End'] %>
  </div>

  <div class="form-group">
      <%= f.label :task, 'Task' %>
      <%= f.text_field :task, :class => "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :status, 'Status' %>
      <%= f.select :status, ['Pending', 'In Progress', 'Done'], selected:'In Progress' %>
  </div>

  <%= f.button :submit, :class => "btn btn-success", name: "project_id",value: @project_id %>
  <%= link_to 'Back', request.referer, class: "btn btn-primary"  %>

<% end %>

app/views/users/index.html.erb
<h1>Unauthorized access</h1>
<%= link_to 'Back', projects_path %>
<% if user_signed_in? %>
  <% if current_user.admin %>
    <h1>All the Users</h1>
    
    <br><br>
    <table class="">
      <tr>
        <th>ID</th>
        <th>User name</th>
      </tr>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'You sure??' } %></td>
          </tr>
      <% end %>
    </table>
    <% end %>
  <% end %>

app/views/users/show.html.erb
<h1>User's Info</h1>
<br>

<h4>Username: <%= @user.username %></h4>
<h4>Email: <%= @user.username %></h4>
<h4>Years of Experience: <%= @user.years_exp %></h4>
<h4>Country: <%= @user.country %></h4>
<h4>Programming skills: <%= @user.prog_lang %></h4>

<br>
<% if user_signed_in? %>
    <% if current_user %>
        <%= link_to 'Edit' ,edit_user_registration_path(@user) ,class: "btn btn-primary" %>
    <% end %>
<% end %>